FROM node:20.19.0-bookworm-slim AS deps

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

FROM deps AS builder

ENV NEXT_TELEMETRY_DISABLED=1

ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_APP_ORIGIN
ARG NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
ARG NEXT_PUBLIC_STRIPE_PRICE_MONTHLY
ARG NEXT_PUBLIC_STRIPE_PRICE_ANNUAL
ARG NEXT_PUBLIC_STRIPE_TRIAL_DAYS
ARG NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
ARG API_PROXY_TARGET

ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_APP_ORIGIN=$NEXT_PUBLIC_APP_ORIGIN
ENV NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=$NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
ENV NEXT_PUBLIC_STRIPE_PRICE_MONTHLY=$NEXT_PUBLIC_STRIPE_PRICE_MONTHLY
ENV NEXT_PUBLIC_STRIPE_PRICE_ANNUAL=$NEXT_PUBLIC_STRIPE_PRICE_ANNUAL
ENV NEXT_PUBLIC_STRIPE_TRIAL_DAYS=$NEXT_PUBLIC_STRIPE_TRIAL_DAYS
ENV NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=$NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
ENV API_PROXY_TARGET=$API_PROXY_TARGET

COPY . .
RUN npm run build

FROM node:20.19.0-bookworm-slim AS runner

WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

COPY --from=builder /app/package.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/next.config.js ./next.config.js

CMD ["npm", "run", "start"]
